# COGS 108 - Data Checkpoint

## Authors
- Jenny Nguyen: Writing - original draft, Data curation, Background research
- Ocean Fang: Background research, Writing - original draft
- James Vidal: Data Curation, Analysis
- Evan Dorton:
- John De Castro: Background research, Data curation

## Research Question

Do individuals who use wearable fitness trackers report greater alignment between perceived and actual physical activity levels, and does this vary by socioeconomic status and health self efficacy?

## Background and Prior Work

<h3>Ideal Dataset</h3>

The ideal dataset for this project would be a large scale cross sectional survey of consenting U.S. adults capturing variables such as:

- Wearable tracker use - binary variable (yes/no), frequency (daily, weekly, rarely), monitored metrics (steps, calories, heartrate)
- Perceived physical activity - self-rated activity level
- Actual physical activity - validated self-report measure or accelerometer data
- Socioeconomic status (SES) - household income bracket, educational attainment, employment status
- Demographic / controls - age, gender, race/ethnicity, geographic region, BMI

**Observations needed:** 1,000-1,500 respondents or more would be needed to detect the hypothesized effects with sufficient statistical reliability.

**Collection method:** Data would be collected by a random sample survey. The survey should be nationally representative and is adminstered online and by phone. Recruitment would target adult age groups, diverse income, and a wide range of SES factors.

**Storage/organization:** Data would be stored in a CSV format, with one row per respondent and columns for each variable. Personally identifiable information would be removed prior to analysis. 

<h3>Potential Datasets</h3>

1. Health Information National Trends Survey (HINTS)
- Available at: https://hints.cancer.gov/data/default.aspx
- publicly available, no application required
- HINTS is a nationally representative survey administered by the National Cancer Institute that specifically tracks a plethora of health categories. Importantly, in the more recent cycles (since HINTS 5 cycle 3), this includes use of health technology, including wearable devices and fitness apps. It contains variables on fitness tracker ownership and use frequency, perceived health behaviors, health self-efficacy, and sociodemographic characteristics. This makes HINTS the closest real-world match to the ideal dataset for this project. Data is available for immediate download in CSV and SAS formats as well. This would likely serve as the primary dataset for the project.
2. Behavioral Risk Factor Surveillance System (BRFSS)
- Available at: https://www.cdc.gov/brfss/data_documentation/index.htm
- publicly available, no application required
- The BRFSS is an annual CDC telephone survey of over 400,000 U.S. adults, making it one of the largest health-related survey datasets in the world. It includes self-reported physical activity levels, demographic variables, income, education, and health status measures highly relevant to this project. 
It does not directly ask about wearable tracker ownership, physical activity perception and actual activity variables can be operationalized from existing questions. Its enormous sample size makes it exceptionally well-suited for subgroup and moderation analysis by SES. Data is freely downloadable in SAS XPT format and can be converted to CSV for use in Python or R.
3. National Health Interview Survey (NHIS)
- Available at: https://www.cdc.gov/nchs/nhis/documentation/?CDC_AAref_Val=https://www.cdc.gov/nchs/nhis/data--questionnaires-documentation.htm 
- publicly available, no application required
- The NHIS is a large household-based survey conducted annually by the CDC's National Center for Health Statistics, covering over 25,000 households per year. It includes detailed physical activity frequency and duration variables, self-rated health measures, income, education, and insurance status as SES indicators. This set also does not include a direct wearable variable, but it has the richest set of physical activity measurement of the three sets here, and will be used to validate or supplement foundational findings in HINTS.

## Hypothesis

We predict that individuals who use wearable fitness trackers will report greater alignment between their perceived and actual physical activity levels compared to non-users. However, we expect this benefit to be significantly moderated by socioeconomic status (SES) and health self-efficacy. Specifically, we anticipate that higher-SES individuals with greater health self-efficacy will demonstrate the strongest alignment between self perceived and actual activity, while lower-SES individuals will show weaker alignment even when tracker use is present. This reflects disparities in device access, engagement quality, and the social conditions under which feedback loops are effective. This prediction is mainly founded on background studies that show how tracker benefits are most pronounced in supported, resource-rich environments, and that cost and awareness barriers disproportionately limit meaningful tracker engagement.

## Data

### Data overview

Instructions: REPLACE the contents of this cell with descriptions of your actual datasets.

For each dataset include the following information
- Dataset #1
  - Dataset Name:
  - Link to the dataset:
  - Number of observations:
  - Number of variables:
  - Description of the variables most relevant to this project
  - Descriptions of any shortcomings this dataset has with repsect to the project
- Dataset #2 (if you have more than one!)
  - same as above
- etc

Each dataset deserves either a set of bullet points as above or a few sentences if you prefer that method.

If you plan to use multiple datasets, add a few sentences about how you plan to combine these datasets.

- Dataset #1
  - Dataset Name: Health Information National Trends Survey (HINTS)
  - Link to the dataset: https://hints.cancer.gov/data/default.aspx
  - Number of observations: 7,278
  - Number of variables:
  - Description of the variables most relevant to this project
  - Descriptions of any shortcomings this dataset has with repsect to the project
- Dataset #2 (if you have more than one!)
  - same as above
- etc

In [28]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [29]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
%pip install requests tqdm gdown

import sys
sys.path.append('./modules')
import get_data

datafiles = [
    { 'url': 'https://dl.dropboxusercontent.com/scl/fi/nx143pk4tgosig6evul3x/hints7_public.dta?rlkey=csathvka5g82ejmjotv0zcxs8', 'filename':'2024 BRFFS.XPT'},
    { 'url': 'https://dl.dropboxusercontent.com/scl/fi/nx143pk4tgosig6evul3x/hints7_public.dta?rlkey=csathvka5g82ejmjotv0zcxs8', 'filename':'hints7_public.dta'},
]

get_data.get_raw(datafiles, destination_directory='data/00-raw/')

Requirement already satisfied: requests in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (2.33.1)
Requirement already satisfied: tqdm in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (4.67.3)
Requirement already satisfied: gdown in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (6.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (from requests) (2026.2.25)
Requirement already satisfied: colorama in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: beautifulsoup4 in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (from gdown) (4.14.3)
Requirement already satisfied: filelock in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (from gdown) (3.29.0)
Requirement already satisfied: typing-extensions>=4.0 in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (from gdown) (4.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\Users\james\.conda\envs\COGS108_Sp26\Lib\site-packages (from requests[socks]->gdown) (1.7.1)
Note: you may need to restart the kernel to use updated packages.

Overall Download Progress:  50%|█████     | 1/2 [00:04<00:04,  4.70s/it]

Successfully downloaded: 2024 BRFFS.XPT

Overall Download Progress: 100%|██████████| 2/2 [00:09<00:00,  4.88s/it]

Successfully downloaded: hints7_public.dta

### Health device, demographic, and health data

- Dataset #1
  - Dataset Name: Health Information National Trends Survey (HINTS)
  - Link to the dataset: https://hints.cancer.gov/data/default.aspx
  - Number of observations: 7,278
  - Number of variables: 20
  - Description of the variables most relevant to this project
     - WearableDevTrackHealth2, FreqWearDevTrackHealth2, FreqUseInternet, UseDevice_SmWatch - Health device usage and related metrics
     - WeeklyMinutesModerateExercise - actual reported physical activity 
     - OwnAbilityTakeCareHealth - self-efficacy 
     - phq4 - self-reported mental health
     - Age, BirthSex RaceEthn5, etc. - demographic data

   - Descriptions of any shortcomings this dataset has with repsect to the project
     - data is self reported, participants may overestimate or underestimate their exercise habits, wearable usage, alcohol use, or health behaviors 
     - individuals who choose to use fitness trackers may already be more health-conscious or motivated than those who do not

In [5]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
import pandas as pd
import os
os.getcwd()

df = pd.read_stata("data/00-raw/hints7_public.dta")
df.head()
print(df.columns.tolist())

['HHID', 'APP_REGION', 'DRA', 'RUC2003', 'RUC2013', 'RUC2023', 'PR_RUCA_2010', 'NCHSURCODE2013', 'CENSDIV', 'CENSREG', 'STRATUM', 'VAR_STRATUM', 'VAR_CLUSTER', 'FormType', 'Language_Flag', 'NR_FUFLG', 'Treatment_H7_1', 'Treatment_H7_2', 'Updatedate', 'AdultsinHH', 'MailHHAdults', 'CommitmentStmt', 'SeekCancerInfo', 'CancerLotOfEffort', 'CancerFrustrated', 'CancerConcernedQuality', 'CancerTooHardUnderstand', 'CancerTrustDoctor', 'CancerTrustFamily', 'CancerTrustGov', 'CancerTrustCharities', 'CancerTrustReligiousOrgs', 'CancerTrustScientists', 'HealthRecsConflict', 'HealthRecsChange', 'FreqUseInternet', 'Internet_Cell2', 'Internet_HighSpeed2', 'Electronic2_HealthInfo', 'Electronic2_MessageDoc', 'Electronic2_TestResults', 'Electronic2_MadeAppts', 'InternetConnection', 'DigLit_Frustrating', 'DigLit_UseNoHelp', 'DigLit_SearchSkills', 'UseDevice_Computer', 'UseDevice_SmPhone', 'UseDevice_Tablet', 'UseDevice_SmWatch', 'UsedHealthWellnessApps2', 'WearableDevTrackHealth2', 'FreqWearDevTrackHealth2', 'WillingShareData_HCP2', 'SharedHealthDeviceInfo2', 'SocMed_Visited', 'SocMed_SharedPers', 'SocMed_SharedGen', 'SocMed_Interacted', 'SocMed_WatchedVid', 'MisleadingHealthInfo', 'SocMed_MakeDecisions', 'SocMed_DiscussHCP', 'SocMed_TrueFalse', 'SocMed_SameViews', 'HealthInsurance2', 'FreqGoProvider', 'QualityCare', 'ChanceAskQuestions', 'FeelingsAddressed', 'InvolvedDecisions', 'UnderstoodNextSteps', 'ExplainedClearly', 'SpentEnoughTime', 'HelpUncertainty', 'ProbCare_WaitLong2', 'ProbCare_RedoTest', 'TalkedDoctor2', 'DocOpenToInfo', 'DocRespectedInfo', 'DocInteraction', 'ConfidentMedForms', 'TrustHCSystem', 'DiscriminatedMedCare2', 'ManageMultipleProviders', 'UpToDateMultiProv', 'ReceiveTelehealthCare', 'NoTelehealth', 'NoTelehealth_OS', 'Telehealth_HCPRecommended', 'Telehealth_WantedAdvice', 'Telehealth_AvoidExposure', 'Telehealth_Convenient', 'Telehealth_AddtlHCP', 'Telehealth_IncludeOthers', 'Telehealth_Other', 'Telehealth_Other_OS', 'TelehealthReasons_Cat', 'Telehealth_TechProbs', 'Telehealth_GoodCare', 'Telehealth_EasyCare', 'Telehealth_Recommend', 'RecentTelehealthReason2', 'RecentTelehealthReason2_OS', 'WillingUseTelehealth', 'OfferedAccessHCP3', 'OfferedAccessInsurer3', 'HCPEncourageOnlineRec2', 'AccessOnlineRecord3', 'HowAccessOnlineRecord2', 'RecordsOnline2_ViewResults', 'RecordsOnline2_ViewNotes', 'UnderstandOnlineMedRec2', 'OnlinePortal_PCP', 'OnlinePortal_OthHCP', 'OnlinePortal_Insurer', 'OnlinePortal_Lab', 'OnlinePortal_Pharmacy', 'OnlinePortal_Hospital', 'OnlinePortal_NoRec', 'OnlinePortal_Cat', 'UsedPortalOrganizerApp', 'OptionResultsBeforeHCP', 'LookResultsBeforeHCP', 'UnderstandResultsBeforeHCP', 'KnowledgePalliativeCare', 'PCStopTreatments2', 'Caregiving_Parent', 'Caregiving_Spouse', 'Caregiving_Child2', 'Caregiving_AnotherFam', 'Caregiving_Friend', 'Caregiving_No', 'CaregivingWho_Cat', 'Caregiving_Professional', 'Caregiving_Cancer', 'Caregiving_AlzNeuro', 'Caregiving_ShortTerm', 'Caregiving_LongTerm', 'Caregiving_OrthoAging', 'Caregiving_MentalHealth2', 'Caregiving_Other', 'Caregiving_Other_OS', 'Caregiving_NotSure', 'CAREGIVINGCOND_CAT', 'Caregiving_AccessMedRec2', 'HadTest3_Ancestry2', 'HadTest3_PersonalTrait', 'HadTest3_SpecificDisease', 'HadTest3_Prenatal', 'HadTest3_Other', 'HadTest3_Other_OS', 'HadTest3_NotSure', 'HadTest3_NotHad', 'HadTest3_Cat', 'ReasonTest_DocRec', 'ReasonTest_UnderstandFam', 'ReasonTest_FindFam', 'ReasonTest_PersTraits', 'ReasonTest_DiseaseRisk', 'ReasonTest_LearnStrategies', 'ReasonTest_Prenatal', 'ReasonTest_Gift', 'ReasonTest_Other', 'ReasonTest_Other_OS', 'ReasonTest_Cat', 'ConfidentTestAccurate', 'LabShare2_HCP', 'LabShare2_ScientificRes', 'LabShare2_ForProfitCo2', 'LabShare2_LEAgencies', 'LabShare2_HealthIns', 'LabShare2_OthIns', 'LabShare2_NotSure', 'LabShare2_NotShared', 'LabShare2_Cat', 'ExpClinTrial', 'ClinTrials2_HelpingPeople', 'ClinTrials2_ReceiveComp', 'ClinTrials2_DocEncouraged', 'ClinTrials2_FamEncouraged', 'ClinTrials2_GetBetter', 'ClinTrials2_NotDisruptive', 'ClinTrials2_NotWilling', 'ClinTrials2_Cat', 'ClinTrials2_Cnt', 'SusClinTrial', 'GeneralHealth', 'OwnAbilityTakeCareHealth', 'TalkHealthFriends', 'HealthLimits_Deaf', 'HealthLimits_Blind', 'HealthLimits_Mobility', 'HealthLimits_Pain', 'MedConditions_Diabetes', 'MedConditions_HighBP', 'MedConditions_HeartCondition', 'MedConditions_LungDisease', 'MedConditions_Depression', 'Height_Feet', 'Height_Inches', 'Weight', 'SleepWeekdayHr', 'SleepWeekendHr2', 'LittleInterest', 'Hopeless', 'Nervous', 'Worrying', 'FeelLeftOut', 'FeelPeopleBarelyKnow', 'FeelIsolated', 'FeelPeopleNotWithMe', 'TimesModerateExercise', 'HowLongModerateExerciseMinutes', 'TimesStrengthTraining', 'AverageTimeSitting', 'ClimateChgHarmHealth', 'ExtremeWeatherEvents', 'HarmHealth_OutdoorAir', 'HarmHealth_IndoorAir', 'TimesSunburned', 'Sunburned_JobOutside', 'Sunburned_HomeOutside', 'Sunburned_Sunbathing', 'Sunburned_Swimming', 'Sunburned_Exercise', 'Sunburned_SportingEvent', 'Sunburned_OutdoorEvent', 'Sunburned_DayToDay', 'Sunburned_Other', 'Sunburned_DK', 'SunburnedAct_Cat', 'Sunburned_Alcohol2', 'Sunburned_Marijuana', 'CutSkipMeals2', 'CannotAffordMeals2', 'WorryForcedMove2', 'LackTransportation2', 'DiffPayMedBills', 'FinIssues_HCPDocumenting', 'FinIssues_HCPSharing', 'Fruit2', 'Vegetables2', 'FollowMyPlate', 'PreparedMeal_CalInfo', 'DrinkDaysPerMonth', 'DrinksPerDay2', 'DrinksOneOccasion', 'Alcohol_CancerRisk', 'ExcessiveAlcohol2_BanAds', 'ExcessiveAlcohol2_ReqWarn', 'NRTHelpQuit_ENDS', 'NRTHelpQuit_NicPouch', 'NRTHelpQuit_HeatTob', 'NRTHelpQuit_ModRisk', 'NRTHelpQuit_None', 'NRTHelpQuit_DK', 'NRTHelpQuit_Cat', 'SeenFedCourtTobMessages', 'TobMessages_Trusted', 'TobMessages_MoreInf', 'TobMessages_ThoughtQuit', 'TobMessages_ThoughtFam', 'TobMessages_LikedOrder', 'TobMessages_Cat', 'Smoke100', 'SmokeNow', 'EverUsed_ECig', 'EverUsed_Cigars', 'EverUsed_Hookah', 'EverUsed_Smokeless', 'EverUsed_NicPouch', 'EverUsed_HeatTob', 'EverUsed_ModRisk', 'EverUsed_None', 'EverUsed_Cat', 'NowUse_ECig', 'NowUse_Cigars', 'NowUse_Hookah', 'NowUse_Smokeless', 'NowUse_NicPouch', 'NowUse_HeatTob', 'NowUse_ModRisk', 'NowUse_None', 'NowUse_Cat', 'Marijuana_NotUsed', 'Marijuana_Smoking', 'Marijuana_Vaping', 'Marijuana_Dabbing', 'Marijuana_Eating', 'Marijuana_Drinking', 'Marijuana_Lotion', 'MarijuanaUse_Cat', 'MarijuanaUseReason', 'MarijuanaUseEffect', 'COVIDDelayCaScreening', 'DocTalkLDCT', 'DocTellColorectalTests2', 'HeardMultiCaTest', 'ValueMultiCaTest', 'HBVCauseCancer', 'HCVCauseCancer', 'PrefCervCaTest', 'CervCaTest_Work', 'CervCaTest_TranspCost', 'CervCaTest_HCPDistance', 'CervCaTest_Privacy', 'CervCaTest_AvoidEmb', 'CervCaTest_OthReasons', 'CervCaTest_Cat', 'EverythingCauseCancer', 'PreventNotPossible', 'TooManyRecommendations', 'CancerFatal', 'HeardChemoBrain', 'WhichRatioCancerChance2', 'EverHadCancer', 'CaBladder', 'CaBone', 'CaBreast', 'CaBrain', 'CaCervical', 'CaColon', 'CaEndometrial', 'CaEye', 'CaHeadNeck', 'CaLeukemia', 'CaLiver', 'CaLung', 'CaHodgkins', 'CaNonHodgkin', 'CaMelanoma', 'CaMultMyeloma', 'CaOral', 'CaOvarian', 'CaPancreatic', 'CaPharyngeal', 'CaProstate', 'CaRectal', 'CaRenal', 'CaSkin', 'CaStomach', 'CaTesticular', 'CaThyroid', 'CaOther', 'CaOther_OS', 'Cancer_Cat', 'WhenDiagnosedCancer', 'FamilyEverHadCancer2', 'Age', 'BirthSex', 'WorkHrsPerWeek', 'Occupation2_Employed', 'Occupation2_OOW1Y', 'Occupation2_OOWLess1Y', 'Occupation2_Homemaker', 'Occupation2_Student', 'Occupation2_Retired', 'Occupation2_Disabled', 'Occupation2_Other', 'Occupation2_Other_OS', 'Occupation2_Cat', 'FullTimeOcc2_Cat', 'WorkHrs_DidNotWork', 'WorkHrs_EarlyAM', 'WorkHrs_AM', 'WorkHrs_Afternoon', 'WorkHrs_Evening', 'WorkHrs_Night', 'WorkHrs_Cat', 'MaritalStatus', 'Education', 'NotHisp', 'Mexican', 'PuertoRican', 'Cuban', 'OthHisp', 'Hisp_Cat', 'White', 'Black', 'AmerInd', 'AsInd', 'Chinese', 'Filipino', 'Japanese', 'Korean', 'Vietnamese', 'OthAsian', 'OthPacIsl', 'Race_Cat2', 'EthnicGroupBelonging', 'SexualOrientation2', 'SexualOrientation2_OS', 'TotalHousehold', 'R_HHADULTS', 'HHADULTS_NUM', 'ChildrenInHH', 'PoliticalViewpoint', 'IncomeRanges', 'IncomeFeelings', 'PERSON_FINWT0', 'PERSON_FINWT1', 'PERSON_FINWT2', 'PERSON_FINWT3', 'PERSON_FINWT4', 'PERSON_FINWT5', 'PERSON_FINWT6', 'PERSON_FINWT7', 'PERSON_FINWT8', 'PERSON_FINWT9', 'PERSON_FINWT10', 'PERSON_FINWT11', 'PERSON_FINWT12', 'PERSON_FINWT13', 'PERSON_FINWT14', 'PERSON_FINWT15', 'PERSON_FINWT16', 'PERSON_FINWT17', 'PERSON_FINWT18', 'PERSON_FINWT19', 'PERSON_FINWT20', 'PERSON_FINWT21', 'PERSON_FINWT22', 'PERSON_FINWT23', 'PERSON_FINWT24', 'PERSON_FINWT25', 'PERSON_FINWT26', 'PERSON_FINWT27', 'PERSON_FINWT28', 'PERSON_FINWT29', 'PERSON_FINWT30', 'PERSON_FINWT31', 'PERSON_FINWT32', 'PERSON_FINWT33', 'PERSON_FINWT34', 'PERSON_FINWT35', 'PERSON_FINWT36', 'PERSON_FINWT37', 'PERSON_FINWT38', 'PERSON_FINWT39', 'PERSON_FINWT40', 'PERSON_FINWT41', 'PERSON_FINWT42', 'PERSON_FINWT43', 'PERSON_FINWT44', 'PERSON_FINWT45', 'PERSON_FINWT46', 'PERSON_FINWT47', 'PERSON_FINWT48', 'PERSON_FINWT49', 'PERSON_FINWT50', 'AgeGrpA', 'AgeGrpB', 'EducA', 'EducB', 'RaceEthn', 'HHInc', 'BMI', 'TimeSinceDX', 'smokeStat', 'RaceEthn5', 'phq4', 'WeeklyMinutesModerateExercise', 'IncomeRanges_IMP', 'ECigUse', 'AvgDrinksPerWeek', 'PCCScale', 'ISEE_Scale', 'PROMIS_Isolation_t', 'SexualOrientation_Recode']

In [31]:
print(df.shape)
print(df.info())

(7278, 470)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7278 entries, 0 to 7277
Columns: 470 entries, HHID to SexualOrientation_Recode
dtypes: category(403), datetime64[ns](1), float64(53), object(13)
memory usage: 6.7+ MB
None

In [32]:
cols = [
    'WearableDevTrackHealth2',
    'FreqWearDevTrackHealth2',
    'FreqUseInternet',
    'UseDevice_SmWatch',
    'WeeklyMinutesModerateExercise',
    'IncomeRanges_IMP',
    'OwnAbilityTakeCareHealth',
    'phq4',
    'Age',
    'BirthSex',
    'RaceEthn5',
    'RaceEthn',
    'Hisp_Cat',
    'CENSREG',
    'RUC2013',
    'MaritalStatus',
    'PoliticalViewpoint',
    'SexualOrientation_Recode',
    'EducA'
]

df_sub = df[cols]
df_sub.head()

,WearableDevTrackHealth2,FreqWearDevTrackHealth2,FreqUseInternet,UseDevice_SmWatch,WeeklyMinutesModerateExercise,IncomeRanges_IMP,OwnAbilityTakeCareHealth,phq4,Age,BirthSex,RaceEthn5,RaceEthn,Hisp_Cat,CENSREG,RUC2013,MaritalStatus,PoliticalViewpoint,SexualOrientation_Recode,EducA
0,I have never used an electronic wearable device,"Inapplicable, coded 2 in WearableDevTrackHealth2",More than once per day,No,225.0,"$100,000 to $199,999",Completely confident,0.0,69.0,Male,Non-Hispanic White,Non-Hispanic White,Not Hispanic only,South,Metro - Counties in metro areas of 1 million p...,Married,Moderate,"Straight, that is, not gay or lesbian",College Graduate or More
1,Yes,everyday,More than once per day,Yes,180.0,"$200,000 or more",Completely confident,0.0,62.0,Female,Non-Hispanic White,Non-Hispanic White,Not Hispanic only,South,Metro - Counties in metro areas of 1 million p...,Married,Somewhat Conservative,"Straight, that is, not gay or lesbian",Some College
2,Yes,everyday,More than once per day,Yes,240.0,"$75,000 to $99,999",Somewhat confident,4.0,34.0,Female,Hispanic,Hispanic,Other Hispanic only,West,Metro - Counties in metro areas of 1 million p...,Married,Somewhat Conservative,"Straight, that is, not gay or lesbian",College Graduate or More
3,"No, not in the past 12 months","Inapplicable, coded 2 in WearableDevTrackHealth2",More than once per day,No,120.0,"$50,000 to $74,999",Somewhat confident,4.0,65.0,Male,Non-Hispanic White,Non-Hispanic White,Not Hispanic only,Northeast,Metro - Counties in metro areas of 1 million p...,Married,Moderate,"Straight, that is, not gay or lesbian",Some College
4,I have never used an electronic wearable device,Question answered in error (Commission Error),More than once per day,No,0.0,"$0 to $9,999",Somewhat confident,11.0,64.0,Female,Non-Hispanic White,Non-Hispanic White,Not Hispanic only,Northeast,Metro - Counties in metro areas of 1 million p...,"Single, never been married",Liberal,"Straight, that is, not gay or lesbian",College Graduate or More

In [33]:
df_sub['WearableDevTrackHealth2'] = df_sub['WearableDevTrackHealth2'].replace({
    'I have never used an electronic wearable device': 'No',
    'No, not in the past 12 months': 'No'
})

df_sub['FreqWearDevTrackHealth2'] = df_sub['FreqWearDevTrackHealth2'].replace({
    'Inapplicable, coded 2 in WearableDevTrackHealth2': 'No wearable use'
})

remove_vals = [
    'Missing data (Not Ascertained)',
    'Missing data (Web partial - Question Never Seen)',
    'Missing data (Filter Missing)',
    'Unreadable or Nonconforming Numeric Response',
    'Unreadable or Non-conforming numeric response',
    'Question answered in error (Commission Error)',
    'Multiple responses selected in error',
    'Multiple Responses Selected in Error',
    "Don't know"
]



for col in cols:
    df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)

df_sub = df_sub[df_sub['WeeklyMinutesModerateExercise'] != 6300.0]

df_sub = df_sub.dropna(subset=cols)

for col in cols:
    if hasattr(df_sub[col], 'cat'):
        df_sub[col] = df_sub[col].cat.remove_unused_categories()

df_sub.info()
df_sub.value_counts()
df_sub.describe()

C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_sub['WearableDevTrackHealth2'] = df_sub['WearableDevTrackHealth2'].replace({
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub['WearableDevTrackHealth2'] = df_sub['WearableDevTrackHealth2'].replace({
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:6: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_sub['FreqWearDevTrackHealth2'] = df_sub['FreqWearDevTrackHealth2'].replace({
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub['FreqWearDevTrackHealth2'] = df_sub['FreqWearDevTrackHealth2'].replace({
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:25: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:25: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:25: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:25: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:25: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:25: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:25: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)
C:\Users\james\AppData\Local\Temp\ipykernel_17124\271877318.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub[col] = df_sub[col].replace(remove_vals, pd.NA)

<class 'pandas.core.frame.DataFrame'>
Index: 5173 entries, 0 to 7277
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   WearableDevTrackHealth2        5173 non-null   category
 1   FreqWearDevTrackHealth2        5173 non-null   category
 2   FreqUseInternet                5173 non-null   category
 3   UseDevice_SmWatch              5173 non-null   category
 4   WeeklyMinutesModerateExercise  5173 non-null   category
 5   IncomeRanges_IMP               5173 non-null   category
 6   OwnAbilityTakeCareHealth       5173 non-null   category
 7   phq4                           5173 non-null   category
 8   Age                            5173 non-null   category
 9   BirthSex                       5173 non-null   category
 10  RaceEthn5                      5173 non-null   category
 11  RaceEthn                       5173 non-null   category
 12  Hisp_Cat                       5173 non-null   category
 13  CENSREG                        5173 non-null   category
 14  RUC2013                        5173 non-null   category
 15  MaritalStatus                  5173 non-null   category
 16  PoliticalViewpoint             5173 non-null   category
 17  SexualOrientation_Recode       5173 non-null   category
 18  EducA                          5173 non-null   category
dtypes: category(19)
memory usage: 143.9 KB

,WearableDevTrackHealth2,FreqWearDevTrackHealth2,FreqUseInternet,UseDevice_SmWatch,WeeklyMinutesModerateExercise,IncomeRanges_IMP,OwnAbilityTakeCareHealth,phq4,Age,BirthSex,RaceEthn5,RaceEthn,Hisp_Cat,CENSREG,RUC2013,MaritalStatus,PoliticalViewpoint,SexualOrientation_Recode,EducA
count,5173,5173,5173,5173,5173.0,5173,5173,5173.0,5173.0,5173,5173,5173,5173,5173,5173,5173,5173,5173,5173
unique,2,6,6,2,135.0,9,5,13.0,81.0,2,5,7,6,4,9,6,7,4,4
top,No,No wearable use,More than once per day,No,0.0,"$100,000 to $199,999",Very confident,0.0,70.0,Female,Non-Hispanic White,Non-Hispanic White,Not Hispanic only,South,Metro - Counties in metro areas of 1 million p...,Married,Moderate,"Straight, that is, not gay or lesbian",College Graduate or More
freq,2980,2980,4418,3192,1155.0,1183,2329,2278.0,127.0,3058,2984,2984,4200,2372,3139,2451,1823,4769,2695

In [34]:
df_sub.to_csv("data/02-processed/hints7_cleaned_v2.csv", index=False)

### Behavioral dataset

 - Dataset Name: Behavioral Risk Factor Surveillance System (BRFSS) - 2024
 - Link to Dataset: https://www.cdc.gov/brfss/data_documentation/index.htm
 - Number of Observations: 457,670 respondents
 - Number of Variables: 345 variables
 - Description of Variables Most Relevant to This Project: 
   - Exercise in Past 30 Days (EXERANY2) - Indicates whether respondents participated in physical activities or exercise outside of regular employment during the past month. Responses are categorical (1 = Yes, 2 = No). Approximately 77% of respondents reported exercising in the past 30 days.
   - Income Level (INCOME3) - Annual household income grouped into income brackets ranging from less than $10,000 to $200,000+. This variable may be useful for measuring socioeconomic status (SES).
   - Education Level (EDUCA) - Highest completed education level, ranging from elementary education to college graduation. This may serve as an additional measure of SES and health literacy.
   - General Health (GENHLTH) - Self-reported health status measured categorically from Excellent to Poor. This may help contextualize physical activity behavior and perceived wellness.
   - Body Mass Index (_BMI5) - Computed BMI derived from respondent height and weight. BMI is reported in kg/m² (with two implied decimal places) and may be useful as a health-related outcome variable.
  - Potential Shortcomings: A major limitation of BRFSS is that the data is self-reported, meaning exercise behavior, health status, and other variables may be subject to reporting bias or inaccuracies. Additionally, the dataset does not appear to directly measure wearable fitness tracker ownership, which is central to our research question. Because of this, wearable usage may need to be approximated through proxy variables or the research question may need to be slightly refined if this dataset is selected. The dataset also contains some missingness and nonresponse patterns. For example, income variables include “Refused” and “Don’t Know” responses, while BMI is missing for respondents who did not provide height or weight measurements.

In [44]:
brffs = pd.read_sas('data/00-raw/2024 BRFFS.XPT')
brffs

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,2.0,b'02282024',b'02',b'28',b'2024',1100.0,b'2024000001',2.024000e+09,1.0,...,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,2.0
1,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000002',2.024000e+09,1.0,...,4.0,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0
2,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000003',2.024000e+09,1.0,...,4.0,2.0,1.0,1.000000e+02,2.0,1.400000e+03,1.0,NaN,NaN,2.0
3,1.0,2.0,b'02282024',b'02',b'28',b'2024',1100.0,b'2024000004',2.024000e+09,1.0,...,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0
4,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000005',2.024000e+09,1.0,...,3.0,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457665,78.0,7.0,b'07122024',b'07',b'12',b'2024',1200.0,b'2024001344',2.024001e+09,NaN,...,NaN,NaN,9.0,9.000000e+02,9.0,9.990000e+04,9.0,9.0,9.0,NaN
457666,78.0,7.0,b'07182024',b'07',b'18',b'2024',1100.0,b'2024001345',2.024001e+09,NaN,...,4.0,2.0,1.0,1.000000e+02,9.0,3.500000e+03,2.0,2.0,2.0,1.0
457667,78.0,7.0,b'07172024',b'07',b'17',b'2024',1100.0,b'2024001346',2.024001e+09,NaN,...,4.0,9.0,1.0,7.000000e+00,1.0,1.400000e+02,1.0,1.0,1.0,2.0
457668,78.0,7.0,b'07202024',b'07',b'20',b'2024',1200.0,b'2024001347',2.024001e+09,NaN,...,NaN,NaN,9.0,9.000000e+02,9.0,9.990000e+04,9.0,NaN,NaN,NaN
457669,78.0,7.0,b'07182024',b'07',b'18',b'2024',1100.0,b'2024001348',2.024001e+09,NaN,...,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,9.0

In [46]:
print(brffs.shape)
print(brffs.info())

(457670, 301)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457670 entries, 0 to 457669
Columns: 301 entries, _STATE to _AIDTST4
dtypes: float64(296), object(5)
memory usage: 1.0+ GB
None

In [49]:
clean_brffs = brffs[['EXERANY2', 'INCOME3', 'EDUCA', 'GENHLTH', '_BMI5']]
new_col = {
    'EXERANY2': 'Exercise', 
    'INCOME3': 'Income', 
    'EDUCA': 'Education', 
    'GENHLTH': 'General Health', 
    '_BMI5': 'BMI'
}
clean_brffs = clean_brffs.rename(columns=new_col)
clean_brffs = clean_brffs.dropna()
clean_brffs

        Exercise  Income  Education  General Health     BMI
0            1.0    99.0        4.0             3.0  2249.0
1            1.0    11.0        6.0             1.0  2583.0
2            1.0    99.0        5.0             2.0  2253.0
3            1.0     6.0        6.0             1.0  2509.0
4            2.0     3.0        5.0             3.0  1977.0
...          ...     ...        ...             ...     ...
457664       2.0     2.0        4.0             5.0  2986.0
457666       2.0     6.0        2.0             4.0  2066.0
457667       2.0     8.0        6.0             3.0  2437.0
457668       1.0    10.0        5.0             1.0  2441.0
457669       1.0     5.0        2.0             3.0  2647.0

[414628 rows x 5 columns]

In [50]:
clean_brffs.info()
clean_brffs.value_counts()
clean_brffs.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 414628 entries, 0 to 457669
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Exercise        414628 non-null  float64
 1   Income          414628 non-null  float64
 2   Education       414628 non-null  float64
 3   General Health  414628 non-null  float64
 4   BMI             414628 non-null  float64
dtypes: float64(5)
memory usage: 19.0 MB

,Exercise,Income,Education,General Health,BMI
count,414628.000000,414628.000000,414628.000000,414628.000000,414628.000000
mean,1.243271,19.397433,5.054135,2.654618,2855.684180
std,0.525976,29.476651,1.020691,1.076759,658.616736
min,1.000000,1.000000,1.000000,1.000000,1200.000000
25%,1.000000,6.000000,4.000000,2.000000,2414.000000
50%,1.000000,8.000000,5.000000,3.000000,2744.000000
75%,1.000000,10.000000,6.000000,3.000000,3175.000000
max,9.000000,99.000000,9.000000,9.000000,9984.000000

In [51]:
clean_brffs.to_csv("data/02-processed/brffs.csv", index=False)

## Ethics 

Instructions: Keep the contents of this cell. For each item on the checklist
-  put an X there if you've considered the item
-  IF THE ITEM IS RELEVANT place a short paragraph after the checklist item discussing the issue.
  
Items on this checklist are meant to provoke discussion among good-faith actors who take their ethical responsibilities seriously. Your teams will document these discussions and decisions for posterity using this section.  You don't have to solve these problems, you just have to acknowledge any potential harm no matter how unlikely.

Here is a [list of real world examples](https://deon.drivendata.org/examples/) for each item in the checklist that can refer to.

[![Deon badge](https://img.shields.io/badge/ethics%20checklist-deon-brightgreen.svg?style=popout-square)](http://deon.drivendata.org/)

### A. Data Collection
 - [X] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent?

> Yes, the datasets were in fact collected with informed consent from all participants. Each participants were indeed made aware of the utilization of their data they consented to, which would be used for research purposes. 

 - [X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?

> Since the datasets were survey-based, it would be resonable to suggest that they may have collection bias due to sampling methods, varying question interpretations, and other means. Due to this, we will acknowledge these possible biases and account for them during result interpretation.

 - [X] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?

> The datasets being used have already been de-identified prior to their public release in order to prevent unwanted exposure of all participants personally identifiable information. We will only be using variables relevant to our research question and have no motivation in attempting to re-identify individuals.

 - [X] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?

> Our research requires we look at demographic variables such as socioeconomic status, education, and possibly race in our analysis in order to evaluate how relationsups differ across groups. Doing so will enable us to highlight and discuss possible disparities amongst groups. 

### B. Data Storage
 - [X] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?

> The data we will work with are publicly available and have been de-identified, but we will continue to follow best practices for secure storage and restricted sharing. 

 - [ ] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?
 - [ ] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?

### C. Analysis
 - [X] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?

> We acknowledge limitations, such as not fully capturing data from underrepresented populations and those without access to technology, and as such we will avoid overgeneralizing our findings to populations that are not well represented in our findings.

 - [X] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?

> Yes, we consider the possible biases and will account for them when interpreting the results. Since the datasets are survey based, we are aware it may contain self-reporting bias, social desirability bias, and over estimations of physical activity and will account for them. 

 - [X] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?

> Our group will present these results using all appropriate statistical methods with clearly labeled vizualizations in order to avoid misleading interpretations and honestly represent the data as much as possible. 

 - [X] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?

> Yes, since these datasets are de-identified prior to publication, these are minimal privacy risks. If at any instance PII data is discovered, we have no intention to display it and will not be included them in our findings. 

 - [X] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?

> Yes, all analysis will be well documented and maintained through our GitHub repository, which will allow for reproducibility and transperancy. If issues do come up, all results will be able to be reviewed and verified. 


### D. Modeling
 - [X] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory?

> We acknlowedge certain status variables, such as income and education, may act as proxies for other protected characteristics, and we will be cautious when viewing and interpreting such variables to avoid harmful conclusions that reinforce stereotypes. 

 - [X] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?

> Our intention is to examine any differences among socioeconomic groups and report on any disparities found. In doing such, we will consider if our findings may have unequal implications across groups. 

 - [ ] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?
 - [ ] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?
 - [X] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?

> We will clearly communicate the limitations of our analysis, such as biases in the survey data, limitations to certain measurments in activities, and constraints in establishing casaul relationships. 


### E. Deployment
 - [ ] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?
 - [ ] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?
 - [ ] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary?
 - [ ] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?
Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

* *Primary communication will be through iMessage; all members are expected to respond in the form*
* *All members are expected to contribute equally to the project and individual tasks should be completeed at least 24 hours before the team deadline so there is time for review and integration*
* *All work pushed to the GitHub should be clean, commented, and readable before submission*Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 4/20  |  11 AM | Read & Think about COGS 108 expectations; brainstorm topics/questions  | Determine best form of communication; Discuss and decide on final project topic; discuss hypothesis; begin background research | 
| 4/22  |  11 AM |  Do background research on topic | Discuss ideal dataset(s) and ethics; draft project proposal | 
| 4/29  | 11 AM  | Edit, finalize, and submit proposal; Search for datasets  | Discuss Wrangling and possible analytical approaches; Assign group members to lead each specific part   |
| 5/10  | 11 AM  | Import & Wrangle Data (Ant Man); EDA (Hulk) | Review/Edit wrangling/EDA; Discuss Analysis Plan; Checkpoint #1   |
| 5/25  | 12 PM  | Finalize wrangling/EDA; Begin Analysis (Iron Man; Thor) | Discuss/edit Analysis; Complete project check-in for Checkpoint #2 |
| 5/29  | 12 PM  | Complete analysis; Draft results/conclusion/discussion (Wasp)| Discuss/edit full project |
| 6/9  | Before 11:59 PM  | Final edits, video | Turn in Final Project & Group Project Surveys |